### ISSUE TITLE
Namespace 'say' is already defined

### ISSUE THREAD

**Issue by developeruz** [solanolabs/solano#42]
I get this error after the fresh installation of `solano` gem. Install completes ok, but every `solano` command, even just `solano` without any arguments ends up with this:
```
$ solano
/Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api/api.rb:301:in `namespace': namespace 'say' is already defined (ArgumentError)
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api/client.rb:61:in `<class:Client>'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api/client.rb:4:in `<module:Github>'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api/client.rb:3:in `<top (required)>'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api.rb:78:in `block in require_all'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api.rb:77:in `each'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api.rb:77:in `require_all'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api.rb:113:in `<module:Github>'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/github_api-0.14.2/lib/github_api.rb:15:in `<top (required)>'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solano-1.28.4/lib/solano/cli.rb:13:in `<top (required)>'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/elle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solano-1.28.4/bin/solano:28:in `<top (required)>'
	from /Users/elle/.rbenv/versions/2.3.1/bin/solano:23:in `load'
	from /Users/elle/.rbenv/versions/2.3.1/bin/solano:23:in `<main>'
```

Ruby version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
Bundler version 1.12.5
OS X El Capitan 10.11.5

**Comment by wkj** [comment]
@developeruz are you running this in a directory that has a bundle (i.e. ``Gemfile``, ``Gemfile.lock``)?  This stack trace indicates that the wrong version of the ``github_api`` gem is being loaded.

**Comment by developeruz** [comment]
No `Gemfile` or `Gemfile.lock` around, I'm trying to use `solano` cli for my PHP project.

Looks like `solano`'s `gemspec` declares `github_api` dependency [too loosely](https://github.com/solanolabs/solano/blob/master/solano.gemspec#L38). Notation 
```  
s.add_runtime_dependency("github_api", "~> 0.12")
```
basically means "give me the most recent 0.x version of github_api" because `~>` operator is allowed to increment version after the last dot, in this case, it's `12`. If you want to lock minor version and increment patch versions, you should declare your dependency up to patch version, like this:
```
  s.add_runtime_dependency("github_api", "~> 0.12.1") # takes most recent 0.12.x version
```
This happens because Rubygems don't use `Gemfile.lock` for dependency management, only `gemspec` files.
Could you please fix `github_api` dependency notation and bump new gem version, so I could use it? Thank you.

P.S. Since you distribute your client as a gem, probably you should not commit `Gemfile.lock` at all, since you don't control the environment where this gem will operate as advised in this [article by Yehuda Katz](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/).

**Comment by wkj** [comment]
Thanks!  For a variety of reasons, not specifying ``Gemfile.lock`` is a mistake, not least because in fact the gem is necessarily tested with a specific version.  We can update the gemspec and push a new version for you very shortly.

**Comment by wkj** [comment]
@developeruz Please see gem version ``1.28.5``.

**Comment by developeruz** [comment]
Thanks! It works now.

**Comment by wkj** [comment]
Great!  Glad to hear it!
