### ISSUE TITLE
Behavior of solano console is confusing

### ISSUE THREAD

**Issue by claytron** [solanolabs/solano#64]
The `solano console` command is great for starting up a debug console. Unfortunately, it appears to only open a debug console for the most recently run session. When I'm on a branch, I'd expect it to open a console to the latest session for that branch. Looking at the code, this seems possible, but I couldn't find any docs for the API.

Can this command work similarly to `solano run` so that it acts on the current branch?

**Comment by malinovskymax** [comment]
@claytron thank you for your feedback. In the new version of the gem, we made `solano console` behavior  more predictable, and output more verbose. Please see gem version `1.31.7`
